### ISSUE TITLE
what input should we have, forward reads or reverse reads or both?

### ISSUE THREAD

**Issue by jianshu93** [will-rowe/hulk#19]
Hello Hulk developers,

I am curious what input we should offer to hulk sketch for pair-end metagenomic sequencing, interleaved reads, or just forward reads? For mash, I use interleaved reads (both forward and reverse reads).

Thanks,

Jianshu

**Comment by will-rowe** [comment]
Hi Jianshu,

HULK doesn't take into account paired-end information, so you can provide an interleaved file, a FASTQ stream or several files.

Hope that helps,

Will
