### ISSUE TITLE
EncodeSeqFromPreviousKmer would speed up the encoding

### ISSUE THREAD

**Issue by shenwei356** [will-rowe/hulk#4]
Hi Will,

How about adding a function `EncodeSeqFromPreviousKmer` along with  [`EncodeSeq`](https://github.com/will-rowe/hulk/blob/master/src/kmer/kmer.go#L10), it would save some time by just encoding the last base.

I've just tested it in [my repo](https://github.com/shenwei356/unikmer/blob/master/kmer.go#L85):

```
BenchmarkEncodeK32-16                           20000000                52.7 ns/op
BenchmarkEncodeFromPreviousKmerK32-16           200000000               9.37 ns/op
BenchmarkMustEncodeFromPreviousKmerK32-16       1000000000              1.98 ns/op

Wei

**Comment by will-rowe** [comment]
This is a good suggestion - but I am about to merge the dev branch which uses the ntHash function (which already does this). Will run some tests but may discard this suggestion unless you see any reason to keep the encodeseq function over the ntHash?

**Comment by shenwei356** [comment]
That's OK, It was inspired by ntHash.

**Comment by shenwei356** [comment]
Is ntHash faster than the Encode? Any bench by yourself?

**Comment by will-rowe** [comment]
It is but I didn't bench the original encode properly - I just subbed in ntHash to HULK as a quick test and the HULK runtimes got a ~10% speed up. I haven't optimised either though Encode or ntHash fully yet, so hopefully with a bit of effort I can improve here too!
