### ISSUE TITLE
Possible bug in weighted Jaccard distance calculation

### ISSUE THREAD

**Issue by standage** [will-rowe/hulk#5]
I was looking at the code for the weighted Jaccard calculation and I noticed that `weightA` and `weightB` are set to the same value. They are compared subsequently, but never reassigned or altered. This looks like a bug--a copy/paste error perhaps?

https://github.com/will-rowe/hulk/blob/8828bd6499da0eb35f7567a3b40ebba963db1d9b/src/histosketch/histosketch.go#L240-L250

**Comment by will-rowe** [comment]
Ughh, that's an embarrassing one! Thank you very much for spotting that, will fix it now.

**Comment by will-rowe** [comment]
Fixed in b15ac147d5ef0092baeb289713aefd2226a6fb94. Thanks again!
