### ISSUE TITLE
Allow "fa" extension for FASTA input

### ISSUE THREAD

**Issue by kyclark** [will-rowe/hulk#7]
In "cmd/sketch.go":

106         if *fasta == true {
107             suffix1, suffix2 = "fasta", "fna"
108         }

I commonly use/see "fa" as a file extension and this is being rejected here. Maybe use a regex like this?

^f(ast|n)?a$

Which allows fa, fna, fasta.

**Comment by will-rowe** [comment]
Sure- I just don't normally use the .fa extension as there is a bit of ambiguity there and I haven't written much file format checking into HULK yet. I'll add it though as you have requested it and I take your point that a lot of people use this extension!

**Comment by standage** [comment]
I’ll add my vote to support the `.fa` extension.

Looking forward, it might be possible to auto-infer the format (failing if it can’t be inferred) or to support a flag where the user specifies the format. But of course you have to balance this against other (probably more important) priorities.

**Comment by will-rowe** [comment]
Okay - added (db8247d404fd005210efa28570d1c95671cc9a51).

Thanks folks!
