### ISSUE TITLE
"smash" fails if -d does not end in "/"

### ISSUE THREAD

**Issue by kyclark** [will-rowe/hulk#8]
In "src/histosketch/histosketch.go" the glob pattern is created like this:

307         fp := sketchDir + "*.sketch"

But this fails if "sketchDir" does not end in "/". I'm not a Go programmer, but maybe something like https://golang.org/pkg/path/filepath/#example_Join could fix this? Or just append the appropriate directory delimiter ("/", "\") if one is not there?

**Comment by will-rowe** [comment]
This has been bothering me too, thanks for giving me the nudge to fix it

**Comment by will-rowe** [comment]
Fixed in 2b878c9afc3f9376266bcb80c77fc0b842a6a0f7
