### ISSUE TITLE
Sort "smash" sketches for distance matrix

### ISSUE THREAD

**Issue by kyclark** [will-rowe/hulk#9]
Often my input files are named/numbered so that there is some meaning when they are sorted. The output from "smash" does not order the columns, so I get:

Dolphin_8.fa.sketch,Dolphin_1.fa.sketch,Dolphin_2.fa.sketch,Dolphin_3.fa.sketch,Dolphin_4.fa.sketch,Dolphin_6.fa.sketch,Dolphin_7.fa.sketch

When it would help further downstream analysis if the columns were ordered lexicographically. Can you add a "sort" to the output before printing?

**Comment by will-rowe** [comment]
Sure - don't see anything wrong with adding this. Will get on it tomorrow probably. Thanks for the issue - and for the others which I will get around to shortly.

**Comment by will-rowe** [comment]
Have just added this (7e4c96296a97873c16ee548cf8dff17d4d11ec02). Will prepare a release once I have looked into the other issues.

thanks for the suggestion.
